import React, { useEffect, useRef, useState, useMemo } from 'react';
import { TravelPlan, GroundingData, ItineraryDay } from '../types';

interface Props {
  plan: TravelPlan;
  groundingData: GroundingData;
  destinationImage: string | null;
  destinationName: string;
  onReset: () => void;
  onRegenerateImage: () => void;
  isImageLoading: boolean;
}

// Helper to check if window has L defined (Leaflet)
declare global {
  interface Window {
    L: any;
  }
}

const getWeatherIcon = (text: string) => {
    const t = text.toLowerCase();
    if (t.includes('rain') || t.includes('shower') || t.includes('wet') || t.includes('drizzle')) return '🌧️';
    if (t.includes('storm') || t.includes('thunder') || t.includes('lightning')) return '⛈️';
    if (t.includes('snow') || t.includes('ice') || t.includes('cold') || t.includes('freez') || t.includes('winter') || t.includes('frost')) return '❄️';
    if (t.includes('fog') || t.includes('mist') || t.includes('haze')) return '🌫️';
    if (t.includes('cloud') || t.includes('overcast') || t.includes('gray') || t.includes('gloom')) return '☁️';
    if (t.includes('sun') || t.includes('clear') || t.includes('bright') || t.includes('hot') || t.includes('dry') || t.includes('sunny')) return '☀️';
    if (t.includes('wind') || t.includes('breez')) return '💨';
    return '🌤️';
};

const getBookingUrl = (platform: string, hotelName: string, destinationName: string) => {
    const query = encodeURIComponent(`${hotelName} ${destinationName}`);
    const p = platform.toLowerCase();
    if (p.includes('booking')) return `https://www.booking.com/searchresults.html?ss=${query}`;
    if (p.includes('expedia')) return `https://www.expedia.com/Hotel-Search?destination=${encodeURIComponent(destinationName)}&keyword=${encodeURIComponent(hotelName)}`;
    if (p.includes('hotels.com')) return `https://www.hotels.com/search.do?q-destination=${encodeURIComponent(destinationName)}&q-hotel=${encodeURIComponent(hotelName)}`;
    if (p.includes('agoda')) return `https://www.agoda.com/search?text=${query}`;
    if (p.includes('tripadvisor')) return `https://www.tripadvisor.com/Search?q=${query}`;
    return `https://www.google.com/search?q=book+${query}`;
};

const DayCard: React.FC<{ day: ItineraryDay; isOpen: boolean; onToggle: () => void; destinationName: string }> = ({ day, isOpen, onToggle, destinationName }) => {
  
  const handleAddToCalendar = (e: React.MouseEvent) => {
    e.stopPropagation();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() + 1 + (day.day - 1));
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + 1);
    const formatDate = (d: Date) => d.toISOString().replace(/-|:|\.\d\d\d/g, "").substring(0, 8);
    
    const title = encodeURIComponent(`Trip to ${destinationName}: Day ${day.day} - ${day.title}`);
    const details = encodeURIComponent(
        `Morning: ${day.morning}\n\n` +
        `Afternoon: ${day.afternoon}\n\n` +
        `Evening: ${day.evening}\n\n` +
        `Generated by GlobeTrotter AI`
    );
    const location = encodeURIComponent(destinationName);
    
    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&location=${location}&dates=${formatDate(startDate)}/${formatDate(endDate)}`;
    window.open(url, '_blank');
  };

  return (
    <div className={`rounded-xl border overflow-hidden transition-all duration-300 ${isOpen ? 'border-blue-500/50 bg-slate-800/80 shadow-lg shadow-blue-900/20' : 'border-white/10 bg-slate-800/40 hover:bg-slate-800/60'}`}>
      <div className={`w-full flex justify-between items-center transition-colors duration-300 ${isOpen ? 'bg-blue-900/20 border-b border-blue-500/20' : ''}`}>
          <button 
            onClick={onToggle}
            className="flex-1 py-5 px-6 flex items-center justify-between focus:outline-none text-left group"
            aria-expanded={isOpen}
          >
            <div className="flex items-center gap-4">
                <span className={`flex items-center justify-center w-8 h-8 rounded-full transition-colors duration-300 font-bold ${isOpen ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/40' : 'bg-slate-700 text-slate-300 group-hover:bg-slate-600'}`}>
                   {day.day}
                </span>
                <div>
                   <span className={`block text-lg font-semibold transition-colors ${isOpen ? 'text-blue-300' : 'text-slate-200'}`}>{day.title}</span>
                </div>
            </div>
            <div className={`transform transition-transform duration-300 ${isOpen ? 'rotate-180 text-blue-400' : 'text-slate-500'}`}>
                 <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
            </div>
          </button>
          
          <div className="pr-4 border-l border-white/10 pl-4 py-2">
            <button
                onClick={handleAddToCalendar}
                className="p-2 text-slate-400 hover:text-blue-400 hover:bg-white/5 rounded-full transition-all"
                title="Add to Google Calendar"
            >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
            </button>
          </div>
      </div>
      
      <div className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${isOpen ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}>
        <div className="overflow-hidden">
            <div className="p-6 space-y-8">
                {/* Morning */}
                <div className="flex gap-4 group">
                    <div className="flex-shrink-0 pt-1">
                        <div className="w-10 h-10 rounded-full bg-yellow-500/10 flex items-center justify-center text-yellow-400 shadow-sm ring-1 ring-yellow-500/30">
                            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
                        </div>
                    </div>
                    <div>
                         <h4 className="font-bold text-slate-300 text-sm uppercase tracking-wide mb-1">Morning</h4>
                         <p className="text-slate-300 leading-relaxed text-base">{day.morning}</p>
                    </div>
                </div>
                
                {/* Connector Line */}
                <div className="relative pl-5 ml-5 border-l-2 border-white/5 space-y-8">
                     {/* Afternoon */}
                     <div className="flex gap-4 group -ml-[calc(1.25rem+2px)]">
                        <div className="flex-shrink-0 pt-1">
                            <div className="w-10 h-10 rounded-full bg-orange-500/10 flex items-center justify-center text-orange-400 shadow-sm border-4 border-slate-900 ring-1 ring-orange-500/30">
                                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                            </div>
                        </div>
                        <div>
                            <h4 className="font-bold text-slate-300 text-sm uppercase tracking-wide mb-1">Afternoon</h4>
                            <p className="text-slate-300 leading-relaxed text-base">{day.afternoon}</p>
                        </div>
                    </div>

                    {/* Evening */}
                    <div className="flex gap-4 group -ml-[calc(1.25rem+2px)]">
                        <div className="flex-shrink-0 pt-1">
                            <div className="w-10 h-10 rounded-full bg-indigo-500/10 flex items-center justify-center text-indigo-400 shadow-sm border-4 border-slate-900 ring-1 ring-indigo-500/30">
                                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" /></svg>
                            </div>
                        </div>
                        <div>
                            <h4 className="font-bold text-slate-300 text-sm uppercase tracking-wide mb-1">Evening</h4>
                            <p className="text-slate-300 leading-relaxed text-base">{day.evening}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};

const ItineraryView: React.FC<Props> = ({ plan, groundingData, destinationImage, destinationName, onReset, onRegenerateImage, isImageLoading }) => {
  const mapRef = useRef<HTMLDivElement>(null);
  const mapInstance = useRef<any>(null);

  const [expandedDays, setExpandedDays] = useState<number[]>([1]);
  const [isOfflineAvailable, setIsOfflineAvailable] = useState(false);
  const [showOfflineConfirmation, setShowOfflineConfirmation] = useState(false);

  const [showCurrencyConverter, setShowCurrencyConverter] = useState(false);
  const [conversionRate, setConversionRate] = useState<string>("");
  const [amountToConvert, setAmountToConvert] = useState<string>("");
  const [homeCurrencySymbol, setHomeCurrencySymbol] = useState("$");

  const localCurrencySymbol = useMemo(() => {
    const match = plan.budgetEstimate.total.match(/[^0-9.,\s]+/);
    return match ? match[0] : '$';
  }, [plan.budgetEstimate.total]);

  useEffect(() => {
    try {
        const saved = localStorage.getItem('gemini_travel_offline_plan');
        if (saved) {
            const parsed = JSON.parse(saved);
            if (parsed.destinationName === destinationName) {
                setIsOfflineAvailable(true);
            }
        }
    } catch (e) {
        console.warn("Offline check failed", e);
    }
  }, [destinationName]);

  const toggleDay = (dayNum: number) => {
    setExpandedDays(prev => 
      prev.includes(dayNum) 
        ? prev.filter(d => d !== dayNum)
        : [...prev, dayNum]
    );
  };

  const expandAll = () => setExpandedDays(plan.itinerary.map(d => d.day));
  const collapseAll = () => setExpandedDays([]);

  const handleToggleOffline = () => {
    if (isOfflineAvailable) {
        localStorage.removeItem('gemini_travel_offline_plan');
        setIsOfflineAvailable(false);
    } else {
        setShowOfflineConfirmation(true);
    }
  };

  const confirmSaveOffline = () => {
        try {
            const dataToSave = {
                plan,
                groundingData,
                destinationImage,
                destinationName,
                savedAt: new Date().toISOString()
            };
            localStorage.setItem('gemini_travel_offline_plan', JSON.stringify(dataToSave));
            setIsOfflineAvailable(true);
        } catch (e) {
             try {
                const dataToSave = {
                    plan,
                    groundingData,
                    destinationImage: null, 
                    destinationName,
                    savedAt: new Date().toISOString()
                };
                localStorage.setItem('gemini_travel_offline_plan', JSON.stringify(dataToSave));
                setIsOfflineAvailable(true);
                alert("Itinerary saved offline (text only) due to storage limits.");
            } catch (e2) {
                console.error("Save failed", e2);
                alert("Could not save for offline access. Browser storage full.");
            }
        }
        setShowOfflineConfirmation(false);
  };

  // Initialize Map
  useEffect(() => {
    if (!mapRef.current || !window.L) return;
    
    const validPlaces = groundingData.places.filter(p => p.lat !== undefined && p.lng !== undefined);
    if (validPlaces.length === 0) return;

    if (mapInstance.current) {
        mapInstance.current.remove();
        mapInstance.current = null;
    }

    const center = [validPlaces[0].lat, validPlaces[0].lng];
    const map = window.L.map(mapRef.current).setView(center, 12);
    mapInstance.current = map;

    // Use CartoDB Dark Matter tiles for dark theme matching
    window.L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
        subdomains: 'abcd',
        maxZoom: 20
    }).addTo(map);

    const bounds = window.L.latLngBounds([]);
    validPlaces.forEach(place => {
        if (place.lat && place.lng) {
            // Custom marker icon could go here, but default is fine for now
            const marker = window.L.marker([place.lat, place.lng]).addTo(map);
            
            const popupContent = `
                <div class="font-sans min-w-[240px] p-1 text-slate-800">
                    <h3 class="font-bold text-sm mb-2 pb-2 border-b border-slate-200">${place.title}</h3>
                    <p class="text-xs text-slate-600 mb-3 leading-relaxed">${place.description || 'Explore this attraction.'}</p>
                    <div class="flex gap-2">
                        <a href="${place.uri}" target="_blank" class="flex-1 flex items-center justify-center px-3 py-2 text-xs font-bold text-white bg-blue-600 rounded hover:bg-blue-700">View</a>
                    </div>
                </div>
            `;
            marker.bindPopup(popupContent);
            bounds.extend([place.lat, place.lng]);
        }
    });

    if (validPlaces.length > 1) {
        map.fitBounds(bounds, { padding: [50, 50] });
    }

    return () => {
        if (mapInstance.current) {
            mapInstance.current.remove();
            mapInstance.current = null;
        }
    };
  }, [groundingData.places]);

  const hasCoordinates = groundingData.places.some(p => p.lat !== undefined && p.lng !== undefined);

  return (
    <div className="space-y-8 animate-fade-in relative max-w-7xl mx-auto">
      {/* Hero Section */}
      <div className="relative h-[50vh] min-h-[400px] rounded-3xl overflow-hidden shadow-2xl border border-white/10 group">
        {destinationImage ? (
          <img src={destinationImage} alt="Destination" className={`w-full h-full object-cover transform transition-transform duration-[2s] ${isImageLoading ? 'scale-100 opacity-50' : 'group-hover:scale-105 opacity-100'}`} />
        ) : (
          <div className="w-full h-full bg-slate-800 flex items-center justify-center">
             <span className="text-2xl font-bold text-slate-600">{isImageLoading ? 'Generating Visuals...' : 'No Image Available'}</span>
          </div>
        )}
        <div className="absolute inset-0 bg-gradient-to-t from-[#0f172a] via-transparent to-black/30 flex flex-col justify-end p-8 md:p-12">
            <div className="animate-fade-in-up">
                <h1 className="text-4xl md:text-6xl font-bold text-white mb-4 leading-tight drop-shadow-lg">{plan.tripOverview.summary.split('.')[0]}</h1>
                <div className="flex flex-wrap items-center gap-4 text-white/90">
                     <span className="glass-panel px-4 py-2 rounded-full text-sm font-medium border-white/20 backdrop-blur-md">
                        📅 Best Time: {plan.tripOverview.bestTime}
                     </span>
                     <span className="glass-panel px-4 py-2 rounded-full text-sm font-medium border-white/20 backdrop-blur-md flex items-center gap-2">
                        <span className="text-lg">{getWeatherIcon(plan.tripOverview.weatherExpectation)}</span>
                        {plan.tripOverview.weatherExpectation}
                     </span>
                </div>
            </div>
        </div>
        
        <div className="absolute top-6 right-6 flex gap-3 z-10">
             <button
                onClick={onRegenerateImage}
                disabled={isImageLoading}
                className="glass-panel text-white px-3 py-2.5 rounded-full font-medium transition hover:bg-white/20 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
                title="Regenerate Image"
             >
                {isImageLoading ? (
                    <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                    </svg>
                ) : (
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                )}
             </button>

             <button
                onClick={handleToggleOffline}
                className={`glass-panel flex items-center gap-2 px-5 py-2.5 rounded-full font-medium transition hover:bg-white/10 ${
                    isOfflineAvailable ? 'text-green-400 border-green-500/50' : 'text-white'
                }`}
             >
                {isOfflineAvailable ? "Offline Ready" : "Save Offline"}
             </button>
             
             <button 
                onClick={onReset}
                className="glass-panel bg-white/10 hover:bg-white/20 text-white px-5 py-2.5 rounded-full font-medium transition"
             >
                New Search
             </button>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column: Itinerary */}
        <div className="lg:col-span-2 space-y-8">
            <div className="flex justify-between items-end border-b border-white/10 pb-4">
                <h2 className="text-2xl font-bold text-white">Day-by-Day Itinerary</h2>
                <div className="flex gap-4 text-sm">
                    <button onClick={expandAll} className="text-blue-400 hover:text-blue-300 transition-colors">Expand All</button>
                    <button onClick={collapseAll} className="text-blue-400 hover:text-blue-300 transition-colors">Collapse All</button>
                </div>
            </div>
            
            <div className="space-y-4">
                {plan.itinerary.map((day) => (
                    <DayCard 
                        key={day.day} 
                        day={day} 
                        isOpen={expandedDays.includes(day.day)}
                        onToggle={() => toggleDay(day.day)}
                        destinationName={destinationName}
                    />
                ))}
            </div>

            {/* Interactive Map */}
            {hasCoordinates ? (
                <div className="glass-card rounded-2xl overflow-hidden mt-8">
                     <div className="p-4 border-b border-white/10 bg-white/5 flex items-center gap-2">
                        <span className="text-xl">🗺️</span>
                        <h3 className="text-lg font-bold text-white">Interactive Attraction Map</h3>
                     </div>
                     <div ref={mapRef} className="w-full h-96 z-0 relative" />
                </div>
            ) : (
                 <div className="glass-card rounded-2xl p-8 text-center">
                     <div className="w-16 h-16 rounded-full bg-blue-500/20 flex items-center justify-center mx-auto mb-4 text-3xl">🗺️</div>
                     <h3 className="text-xl font-bold text-white mb-2">Explore the Area</h3>
                     <p className="text-slate-400 mb-6">We found great spots, view them on Google Maps.</p>
                     <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-2xl mx-auto">
                        {groundingData.places.map((place, idx) => (
                            <a key={idx} href={place.uri} target="_blank" className="block p-3 bg-slate-800 rounded-lg hover:bg-slate-700 transition text-sm text-blue-300 truncate border border-white/5">{place.title} ↗</a>
                        ))}
                     </div>
                 </div>
            )}
        </div>

        {/* Right Column: Details */}
        <div className="space-y-6">
            
            {/* Budget */}
            <div className="glass-card rounded-2xl p-6 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 rounded-full blur-2xl -z-10"></div>
                <h3 className="text-xl font-bold text-emerald-400 mb-6 flex items-center gap-2">
                    <span>💵</span> Estimated Budget
                </h3>
                <div className="space-y-4 text-sm">
                    <div className="flex justify-between text-slate-300">
                        <span>Accommodation</span>
                        <span className="text-white font-mono">{plan.budgetEstimate.accommodation}</span>
                    </div>
                    <div className="flex justify-between text-slate-300">
                        <span>Food & Dining</span>
                        <span className="text-white font-mono">{plan.budgetEstimate.food}</span>
                    </div>
                    <div className="flex justify-between text-slate-300">
                        <span>Transport</span>
                        <span className="text-white font-mono">{plan.budgetEstimate.transport}</span>
                    </div>
                    <div className="pt-4 border-t border-white/10 flex justify-between text-emerald-400 font-bold text-lg">
                        <span>Total Est.</span>
                        <span>{plan.budgetEstimate.total}</span>
                    </div>
                </div>
            </div>

            {/* Flight Intel */}
            <div className="glass-card rounded-2xl p-6">
                 <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2"><span>✈️</span> Flight Intel</h3>
                 <div className="space-y-3 text-sm">
                    <div>
                        <span className="text-slate-400 block text-xs uppercase tracking-wider mb-1">Best Time to Fly</span>
                        <span className="text-white font-medium">{plan.flightPrediction.cheapestMonths}</span>
                    </div>
                    <div>
                        <span className="text-slate-400 block text-xs uppercase tracking-wider mb-1">Price Range</span>
                        <span className="text-white font-medium">{plan.flightPrediction.priceRange}</span>
                    </div>
                    <div className="pt-2">
                        <p className="text-xs text-blue-300 italic p-3 bg-blue-500/10 rounded-lg border border-blue-500/20">"{plan.flightPrediction.tips}"</p>
                    </div>
                 </div>
            </div>

            {/* Hotels */}
            <div className="glass-card rounded-2xl p-6">
                <h3 className="text-lg font-bold text-white mb-4">🏨 Where to Stay</h3>
                <div className="space-y-6">
                    {plan.hotels.map((hotel, i) => (
                        <div key={i} className="border-b border-white/10 pb-4 last:border-0 last:pb-0">
                            <div className="flex justify-between items-start mb-2">
                                <span className="font-bold text-slate-200">{hotel.name}</span>
                                <span className="text-[10px] bg-white/10 px-2 py-1 rounded text-slate-300 uppercase tracking-wide">{hotel.type}</span>
                            </div>
                            <p className="text-slate-400 text-xs mb-3 leading-relaxed">{hotel.description}</p>
                            
                            {hotel.bookingOptions && hotel.bookingOptions.length > 0 ? (
                                <div className="bg-black/20 rounded p-3 border border-white/5">
                                    <p className="text-[10px] uppercase font-bold text-slate-500 mb-2">Compare Prices</p>
                                    <div className="space-y-2">
                                        {hotel.bookingOptions.map((opt, idx) => (
                                            <div key={idx} className="flex justify-between items-center text-xs">
                                                <span className="text-slate-400">{opt.platform}</span>
                                                <div className="flex items-center gap-2">
                                                    <span className="font-bold text-white">{opt.price}</span>
                                                    <a href={getBookingUrl(opt.platform, hotel.name, destinationName)} target="_blank" className="text-blue-400 hover:text-blue-300">↗</a>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            ) : (
                                <div className="mt-2 text-right">
                                    <a href={getBookingUrl('google', hotel.name, destinationName)} target="_blank" className="text-xs text-blue-400 hover:text-blue-300">Check Availability ↗</a>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {/* Food */}
             <div className="glass-card rounded-2xl p-6">
                <h3 className="text-lg font-bold text-white mb-4">🍽️ Local Flavors</h3>
                <ul className="list-disc list-inside text-sm text-slate-300 space-y-2 mb-4 marker:text-blue-500">
                    {plan.food.recommendations.map((item, i) => <li key={i}>{item}</li>)}
                </ul>
                <div className="bg-white/5 p-3 rounded-lg border border-white/5">
                    <p className="text-xs text-slate-400">Dietary Note: {plan.food.dietaryNotes}</p>
                </div>
            </div>

            {/* Visa & Safety */}
            <div className="glass-card rounded-2xl p-6 border-l-4 border-amber-500">
                <h3 className="text-lg font-bold text-amber-500 mb-4">⚠️ Essentials</h3>
                <div className="mb-4">
                    <p className="text-xs text-slate-400 uppercase tracking-wider mb-1">Visa Policy</p>
                    <p className="text-sm text-slate-200">{plan.visaInfo}</p>
                </div>
                 <div>
                    <p className="text-xs text-slate-400 uppercase tracking-wider mb-1">Safety Tips</p>
                    <ul className="list-disc list-inside text-sm text-slate-200 space-y-1 marker:text-amber-500">
                        {plan.safetyTips.slice(0,3).map((tip, i) => <li key={i}>{tip}</li>)}
                    </ul>
                </div>
            </div>

            {/* Packing */}
            <div className="glass-card rounded-2xl p-6">
                <h3 className="text-lg font-bold text-white mb-4">🎒 Packing List</h3>
                <div className="space-y-2">
                    {plan.packingList.map((item, i) => (
                        <label key={i} className="flex items-center gap-3 cursor-pointer group hover:bg-white/5 p-2 rounded transition">
                            <input type="checkbox" className="rounded border-slate-600 bg-slate-800 text-blue-500 focus:ring-offset-0 focus:ring-blue-500" />
                            <span className="text-sm text-slate-300 group-hover:text-white transition">{item}</span>
                        </label>
                    ))}
                </div>
            </div>

        </div>
      </div>

       {/* Currency Converter Widget */}
       <div className="fixed bottom-6 right-6 z-40 flex flex-col items-end pointer-events-none">
          <div className={`glass-card p-5 mb-4 pointer-events-auto transition-all duration-300 origin-bottom-right w-72 rounded-2xl ${showCurrencyConverter ? 'scale-100 opacity-100 translate-y-0' : 'scale-95 opacity-0 translate-y-4 pointer-events-none'}`}>
              <div className="flex justify-between items-center mb-4 border-b border-white/10 pb-2">
                  <h4 className="font-bold text-white">Currency Calc</h4>
                  <button onClick={() => setShowCurrencyConverter(false)} className="text-slate-400 hover:text-white">✕</button>
              </div>

              <div className="space-y-4">
                <div className="bg-black/20 p-3 rounded-lg border border-white/5">
                    <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2">Exchange Rate</label>
                    <div className="flex items-center gap-2">
                        <span className="text-sm text-slate-400">1 {localCurrencySymbol} = </span>
                        <input 
                            type="number" 
                            inputMode="decimal"
                            value={conversionRate}
                            onChange={(e) => setConversionRate(e.target.value)}
                            className="flex-1 min-w-0 px-2 py-1 bg-slate-800 border border-slate-600 rounded text-sm text-white outline-none focus:border-blue-500"
                            placeholder="Rate"
                        />
                        <select 
                            value={homeCurrencySymbol}
                            onChange={(e) => setHomeCurrencySymbol(e.target.value)}
                            className="bg-transparent text-sm font-medium text-slate-300 focus:outline-none cursor-pointer"
                        >
                            <option value="$" className="bg-slate-800">USD</option>
                            <option value="€" className="bg-slate-800">EUR</option>
                            <option value="£" className="bg-slate-800">GBP</option>
                            <option value="¥" className="bg-slate-800">JPY</option>
                        </select>
                    </div>
                </div>

                <div>
                   <div className="relative">
                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500">{localCurrencySymbol}</span>
                        <input 
                            type="number" 
                            inputMode="decimal"
                            value={amountToConvert}
                            onChange={(e) => setAmountToConvert(e.target.value)}
                            className="w-full pl-8 pr-4 py-2 bg-slate-800 border border-slate-600 rounded-lg text-sm text-white outline-none focus:border-blue-500"
                            placeholder="Amount..."
                        />
                   </div>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-white/10">
                   <span className="text-xs text-slate-500">Result:</span>
                   <span className="text-xl font-bold text-emerald-400 break-all">
                     {amountToConvert && conversionRate && !isNaN(parseFloat(amountToConvert)) && !isNaN(parseFloat(conversionRate))
                        ? `${homeCurrencySymbol}${(parseFloat(amountToConvert) * parseFloat(conversionRate)).toFixed(2)}` 
                        : '---'}
                   </span>
                </div>
              </div>
          </div>

          <button 
            onClick={() => setShowCurrencyConverter(!showCurrencyConverter)}
            className={`pointer-events-auto flex items-center gap-2 px-4 py-3 rounded-full shadow-2xl transition-all transform hover:scale-105 active:scale-95 ${showCurrencyConverter ? 'bg-slate-700 text-white' : 'bg-gradient-to-r from-blue-600 to-purple-600 text-white'}`}
          >
             <span className="text-xl">💱</span>
          </button>
       </div>

       {/* Offline Confirmation Modal */}
       {showOfflineConfirmation && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in">
             <div className="glass-panel bg-[#0f172a] rounded-2xl shadow-2xl max-w-md w-full p-8 border border-white/10 transform transition-all scale-100">
                  <h3 className="text-xl font-bold text-white mb-2">Save Offline?</h3>
                  <p className="text-slate-400 mb-6 text-sm leading-relaxed">
                      Store this itinerary on your device for access without internet. Large images may be excluded if storage is low.
                  </p>
                  
                  <div className="flex justify-end gap-3">
                      <button 
                        onClick={() => setShowOfflineConfirmation(false)}
                        className="px-5 py-2 text-slate-400 hover:text-white transition-colors"
                      >
                          Cancel
                      </button>
                      <button 
                        onClick={confirmSaveOffline}
                        className="px-5 py-2 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-lg transition-all"
                      >
                          Save Itinerary
                      </button>
                  </div>
             </div>
        </div>
      )}
    </div>
  );
};

export default ItineraryView;